# M.Amintoosi

In [36]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[2,3,4,10,11,12,20,25,30]]).transpose()
kmeans = KMeans(n_clusters=2).fit(X)
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 1, 1, 1])

In [37]:
kmeans.cluster_centers_

array([[ 7.],
       [25.]])

In [27]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([1, 1, 1, 0, 0, 0])

In [25]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])

In [21]:
kmeans.predict([[0, 0], [12, 3]])

In [ ]:
X